### PR TITLE
add new util to name route53 zone

### PR DESCRIPTION
**Pull request by ptolemy428**
## Approvals

- [x] Verified
- [x] @TimMoore
- [x] @hebbo
- [x] @ptolemy428
- [x] @iiman

### CODE REVIEW

**Comment by ptolemy428** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TCf81LIv&#x2F;462-add-dns-for-event-hub"> Add DNS for event_hub</a>

**Comment by TimMoore** [comment]
👍

**Comment by TimMoore** [comment]
:+1: on the new changes too

**Comment by iiman** [comment]
Looks good...our test coverage is on the rise...after getting a hug hit when the new codes were added 👍

**Comment by hebbo** [comment]
👍

**Pull request merged**
